cloudsqlproxy:
  enabled: true
  version: "1.16"
  instance_connection: {{ cookiecutter.cloudsqlConnNamePr }}

rbac:
  create: false 
  serviceAccountAnnotations: {
    iam.gke.io/gcp-service-account: "{{ cookiecutter.gsa }}@{{ cookiecutter.gcpProjectIdPr }}.iam.gserviceaccount.com"
    }   
  serviceAccountName: "{{ cookiecutter.ksa }}"
